import glfw
from OpenGL.GL import *
from OpenGL.GLU import *


def plot_circle_points(xc, yc, x, y):
    points = [
        (xc + x, yc + y),
        (xc - x, yc + y),
        (xc + x, yc - y),
        (xc - x, yc - y),
        (xc + y, yc + x),
        (xc - y, yc + x),
        (xc + y, yc - x),
        (xc - y, yc - x)
    ]

    return points


def midpoint_circle(xc, yc, r):

    x = 0
    y = r

    # Initial decision parameter
    p = 1 - r

    points = []

    while x <= y:

        # Generate 8 symmetric points
        points.extend(plot_circle_points(xc, yc, x, y))

        x += 1

        if p < 0:
            # Choose East pixel
            p = p + 2 * x + 1

        else:
            # Choose South-East pixel
            y -= 1
            p = p + 2 * x - 2 * y + 1

    return points


# ---------------- USER INPUT ----------------

xc = int(input("Enter center x (xc): "))
yc = int(input("Enter center y (yc): "))
r = int(input("Enter radius: "))


# Generate circle pixels
points = midpoint_circle(xc, yc, r)


# Display generated pixels
print("\nPixels generated by Midpoint Circle Algorithm:")

for point in points:
    print(point)


# ---------------- GLFW INITIALIZATION ----------------

if not glfw.init():
    raise Exception("GLFW initialization failed")


window = glfw.create_window(
    800,
    600,
    "Midpoint Circle Drawing Algorithm",
    None,
    None
)

if not window:
    glfw.terminate()
    raise Exception("GLFW window creation failed")


glfw.make_context_current(window)


# ---------------- OPENGL SETUP ----------------

glClearColor(0.0, 0.0, 0.0, 1.0)

glMatrixMode(GL_PROJECTION)
glLoadIdentity()

gluOrtho2D(0, 800, 0, 600)

glMatrixMode(GL_MODELVIEW)
glLoadIdentity()


# ---------------- DRAW CIRCLE ----------------

while not glfw.window_should_close(window):

    glClear(GL_COLOR_BUFFER_BIT)

    # Pixel size
    glPointSize(4)

    # Circle color - white
    glColor3f(1.0, 1.0, 1.0)

    glBegin(GL_POINTS)

    for x, y in points:
        glVertex2i(x, y)

    glEnd()

    glfw.swap_buffers(window)

    glfw.poll_events()


glfw.terminate()